---
version: "2.1"
services:
  calibre-web:
    build: ./
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=969
      - TZ=Etc/UTC
      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - /home/hzf/dotfiles/calibre-web:/config
      - /home/hzf/Documents/Calibre_Library:/books
    ports:
      - 8083:8083
    restart: unless-stopped
