---
services:
  nginx:
    build: .
    container_name: nginx
    # environment:
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx.conf.d:/etc/nginx/conf.d
      - ./html:/etc/nginx/html/
      - ./logs:/var/log/nginx
    # ports:
      # - 80:80
    network_mode: host
    restart: unless-stopped
  # php-fpm:
